-- MySQL Script generated by MySQL Workbench
-- Sat Apr  6 16:30:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 ;
USE `tcc` ;

-- -----------------------------------------------------
-- Table `tcc`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`equipe` (
  `idequipe` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idequipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`projeto` (
  `idprojeto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `idequipe` INT NOT NULL,
  PRIMARY KEY (`idprojeto`),
  INDEX `fk_projeto_equipe1_idx` (`idequipe` ASC) VISIBLE,
  CONSTRAINT `fk_projeto_equipe1`
    FOREIGN KEY (`idequipe`)
    REFERENCES `tcc`.`equipe` (`idequipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`credencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`credencial` (
  `idcredencial` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idcredencial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `idcredencial` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_credencial_idx` (`idcredencial` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_credencial`
    FOREIGN KEY (`idcredencial`)
    REFERENCES `tcc`.`credencial` (`idcredencial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`equipeuso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`equipeuso` (
  `idequipeuso` INT NOT NULL AUTO_INCREMENT,
  `idequipe` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idequipeuso`, `idequipe`, `idusuario`),
  INDEX `fk_equipe_has_usuario_usuario1_idx` (`idusuario` ASC) VISIBLE,
  INDEX `fk_equipe_has_usuario_equipe1_idx` (`idequipe` ASC) VISIBLE,
  CONSTRAINT `fk_equipe_has_usuario_equipe1`
    FOREIGN KEY (`idequipe`)
    REFERENCES `tcc`.`equipe` (`idequipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_has_usuario_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `tcc`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`usopesquisados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`usopesquisados` (
  `idusopesquisados` INT NOT NULL AUTO_INCREMENT,
  `idprojeto` INT NOT NULL,
  PRIMARY KEY (`idusopesquisados`),
  INDEX `fk_usopesquisados_projeto1_idx` (`idprojeto` ASC) VISIBLE,
  CONSTRAINT `fk_usopesquisados_projeto1`
    FOREIGN KEY (`idprojeto`)
    REFERENCES `tcc`.`projeto` (`idprojeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`registronavegacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`registronavegacao` (
  `idregistronavegacao` INT NOT NULL AUTO_INCREMENT,
  `idusopesquisados` INT NOT NULL,
  `idprojeto` INT NOT NULL,
  PRIMARY KEY (`idregistronavegacao`),
  INDEX `fk_registronavegacao_usopesquisados1_idx` (`idusopesquisados` ASC) VISIBLE,
  INDEX `fk_registronavegacao_projeto1_idx` (`idprojeto` ASC) VISIBLE,
  CONSTRAINT `fk_registronavegacao_usopesquisados1`
    FOREIGN KEY (`idusopesquisados`)
    REFERENCES `tcc`.`usopesquisados` (`idusopesquisados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registronavegacao_projeto1`
    FOREIGN KEY (`idprojeto`)
    REFERENCES `tcc`.`projeto` (`idprojeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`tempodominio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`tempodominio` (
  `idtempodominio` INT NOT NULL AUTO_INCREMENT,
  `idusopesquisados` INT NOT NULL,
  `idprojeto` INT NOT NULL,
  PRIMARY KEY (`idtempodominio`),
  INDEX `fk_tempodominio_usopesquisados1_idx` (`idusopesquisados` ASC) VISIBLE,
  INDEX `fk_tempodominio_projeto1_idx` (`idprojeto` ASC) VISIBLE,
  CONSTRAINT `fk_tempodominio_usopesquisados1`
    FOREIGN KEY (`idusopesquisados`)
    REFERENCES `tcc`.`usopesquisados` (`idusopesquisados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tempodominio_projeto1`
    FOREIGN KEY (`idprojeto`)
    REFERENCES `tcc`.`projeto` (`idprojeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
